In [ ]:
import torch
import pandas as pd
import numpy as np 
import matplotlib.pyplot as plt 
print(torch.__version__)

2.0.0+cu118


In [ ]:
## Introduction to Tensors

### Creating Tensors
#PyTorch tensors are created using torch.Tensor()
# Scalar
scalar = torch.tensor(7)
scalar

tensor(7)

In [ ]:
scalar.ndim

0

In [ ]:
# Float 32 tensor
float_32_tensor = torch.tensor([3.0,6.0,9.0],dtype=None)
float_32_tensor

tensor([3., 6., 9.])

In [ ]:
float_32_tensor.dtype

torch.float32

In [ ]:
some_tensor = torch.rand(3,4)
some_tensor

tensor([[0.6221, 0.7007, 0.2392, 0.1962],
        [0.7077, 0.5361, 0.2226, 0.0541],
        [0.6853, 0.7386, 0.8011, 0.5262]])

In [ ]:
print(f"datatype of tensor: {some_tensor.dtype}")
print(f"Shape of tensor: {some_tensor.shape}")

datatype of tensor: torch.float32
Shape of tensor: torch.Size([3, 4])


In [ ]:
### Manipulating Tensors (tensor operations)

Tensor operations include:
*Addition 
*Subtraction 
*Matrix Multiplication 


In [ ]:
# Create a tensor 
tensor = torch.tensor([1,2,3])
tensor+10
tensor*10
tensor

tensor([1, 2, 3])

In [ ]:
tensor * 10
tensor


tensor([1, 2, 3])

In [ ]:
torch.mul(tensor,10)

tensor([10, 20, 30])

In [ ]:
## Finding the min, max, sum etc (tensor aggregation)

x = torch.arange(0, 100, 10)
x

tensor([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

In [ ]:
torch.mean(x.type(torch.float32)), x.type(torch.float32).mean()


(tensor(45.), tensor(45.))

In [ ]:
torch.min(x)

tensor(0)

In [ ]:
# Create *known* parameters
weight =0.7 
bias = 0.3 

# Create 
start=0
end = 1 
step =0.02
X = torch.arange(start,end,step).unsqueeze(dim=1)
y= weight*X+bias

X[:10], y[:10]


(tensor([[0.0000],
         [0.0200],
         [0.0400],
         [0.0600],
         [0.0800],
         [0.1000],
         [0.1200],
         [0.1400],
         [0.1600],
         [0.1800]]),
 tensor([[0.3000],
         [0.3140],
         [0.3280],
         [0.3420],
         [0.3560],
         [0.3700],
         [0.3840],
         [0.3980],
         [0.4120],
         [0.4260]]))

In [ ]:
### Splitting data into training and test sets (one of the most important concepts)

In [ ]:
# Create a train/test split 
train_split  = int(0.8*len(X))
X_train, y_train = X[:train_split], y[:train_split]
X_test, y_test = X[train_split:], y[train_split:]

len(X_train),len(y_train),len(X_test),len(y_test)

(40, 40, 10, 10)

In [ ]:
X_train, y_train

(tensor([[0.0000],
         [0.0200],
         [0.0400],
         [0.0600],
         [0.0800],
         [0.1000],
         [0.1200],
         [0.1400],
         [0.1600],
         [0.1800],
         [0.2000],
         [0.2200],
         [0.2400],
         [0.2600],
         [0.2800],
         [0.3000],
         [0.3200],
         [0.3400],
         [0.3600],
         [0.3800],
         [0.4000],
         [0.4200],
         [0.4400],
         [0.4600],
         [0.4800],
         [0.5000],
         [0.5200],
         [0.5400],
         [0.5600],
         [0.5800],
         [0.6000],
         [0.6200],
         [0.6400],
         [0.6600],
         [0.6800],
         [0.7000],
         [0.7200],
         [0.7400],
         [0.7600],
         [0.7800]]),
 tensor([[0.3000],
         [0.3140],
         [0.3280],
         [0.3420],
         [0.3560],
         [0.3700],
         [0.3840],
         [0.3980],
         [0.4120],
         [0.4260],
         [0.4400],
         [0.4540],
         [

How might we better visualize our data?

THis is where the data explorers motto comes in!

"Visualize, vizualize, vizualize!"



In [ ]:
def plot_predictions (train_data=X_train, 
                      train_labels=y_train, 
                      test_data=X_test, 
                      test_labels=y_test, 
                      predictions=None):
  """
  Plots training data, test data and compares predictions
  """
  plt.figure(figsize=(10,7))

  # Plot training data in blue 
  plt.scatter(train_data, train_labels, c="b",s=4, label="Training Dataset")

In [ ]:
plt.scatter(test_data, test_labels, c ="g", s=4, label="Testing data")
if predictions is not None:
 # Plot the predictions if they exist
 plt.scatter(test_data,predictions,c="r", s=4, label="Predictions")

 plt.legend(prop{"size": 14});
 

SyntaxError: ignored